const VIDEO_TUTORIAL_ID = 'BAACAgIAAxkBAAM1YfiADpkdQMMIgz8iZ0LR6YS5p9wAAnATAAJEAcFLsSFPthp6oukjBA';
const VIDEO_TUTORIAL_CAPTION = 'Видеоинструкция / Video tutorial';

const ENGLISH_HELP_TEXT = "🇷🇺 Выше вы можете найти инструкцию на русском\n\nThe purpose of this bot is to simplify the process of sharing music between users of different streaming platforms. This is an inline bot and it’s not designed for interaction via private messages. You can use it in any of your chats, groups or channels – it doesn't matter, whether the bot is a member or not. To share song with it, watch a short video tutorial to see the bot in action or just follow these simple steps:\n\n1. Copy the link of the song in your streaming service app (this option is in the \"share\" menu)\n2. Type @MusVertBot in chat and paste the link you copied in the previous step\n3. Click on appeared pop-up\n\nDone! You sent a message with song information and links to different streaming platforms! Your friends can click on the button of the streaming platform they use and immediately listen to the song without wasting time searching for it by name. Currently only YouTube Music and Spotify are supported. If you like this bot, but use a different service, join the support chat and tell us about it! We will definitely add support for your favorite service.";
const RUSSIAN_HELP_TEXT = '🇬🇧 Scroll down for an English version of this message\n\nЭтот бот был создан для того, чтобы пользователям разных стриминговых платформ было проще делиться музыкой друг с другом! Это инлайн бот, он не подразумевает взаимодействия с ним через личные сообщения. Вы можете использовать его в любом чате, группе или канале - ему не нужно быть учасником. Чтобы поделиться песней с его помощью, посмотрите короткое видео или просто выполните следующие шаги:\n\n1. Скопируйте ссылку на песню в приложении вашей стриминговой платформы (это опция находится в меню “Поделиться”)\n2. Введите @MusVertBot в чате, нажмите пробел и вставьте ссылку, которую вы скопировали в прошлом шаге.\n3. Кликните на появившееся окошко\n\nГотово! Вы отправили сообщение с информацией о песне и ссылками на разные стриминговые платформы. Ваши друзья могут нажать на кнопку используемой ими стриминговой платформы и сразу же послушать песню, не тратя время на ее поиски. На данный момент поддерживается YouTube Music и Spotify. Если вам понравился бот, но вы пользуетесь другим сервисом, вступайте в чат поддержки и расскажите нам об этом! Мы обязательно добавим поддержку вашего любимого сервиса.';

const CHAT_INVITE_TEXT = 'Есть вопрос или возникла проблема? Обращайтесь в наш чат:\n@MusVertBotSupport\n\nFeel free to ask any questions in our support chat: @MusVertBotSupport';

const SENTRY_DSN = 'https://d29f9a7cfd0b4c04bdc421c092dabae0@o1127561.ingest.sentry.io/6169806';

module.exports = {
  VIDEO_TUTORIAL_ID,
  VIDEO_TUTORIAL_CAPTION,
  RUSSIAN_HELP_TEXT,
  ENGLISH_HELP_TEXT,
  CHAT_INVITE_TEXT,
  SENTRY_DSN,
};
