name: Build & deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/music-share-bot:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Pull image and run app containter on VPS
        uses: appleboy/ssh-action@master
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          BOT_DOMAIN: ${{ secrets.BOT_DOMAIN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }} 
          password: ${{ secrets.VPS_PASSWORD }}
          envs: BOT_TOKEN, SPOTIFY_USERNAME, SPOTIFY_PASSWORD, YT_API_KEY, DOCKER_HUB_TOKEN, BOT_DOMAIN
          script: |
            cd music-share-bot
            echo $DOCKER_HUB_TOKEN | /snap/bin/docker login -u ihorbeliasnyk --password-stdin
            /snap/bin/docker-compose pull nodejs
            /snap/bin/docker-compose up -d --no-deps nodejs
      
